### ISSUE TITLE
Work on documenting our code

### ISSUE THREAD

**Issue by marikaswanberg** [reed-college/paneity#160]
I'm not completely sure what that entails, but probably adding docstrings and comments

**Comment by Gastove** [comment]
@marikaswanberg you got it. Good news: a lot of your code is solid. More comments would be good, though -- in particular: 

- [ ] Places like [this sort of weird function/import](https://github.com/reed-college/paneity/blob/master/tutor/apps.py#L8) (it's not easy to intuit What Do there)
- [ ] all yer javascripts in `tutor/static/js`
