### ISSUE TITLE
Document Spirit a little more clearly

### ISSUE THREAD

**Issue by Gastove** [reed-college/paneity#227]
In particular: why fork and vendor it? What have you changed?

**Comment by marikaswanberg** [comment]
Is there a particular place we should have documentation about this?

**Comment by Gastove** [comment]
Given your use of your wiki, I'd probably write the documentation there, then link to it from your swrrt new readme (probably something like, "Spirit is a modern Python based forum... forum application, which we have forked; our fork is <here>, notes on the decision to fork <here>". Could do it as a footnote instead of a clause at the end of the sentence? Something around like that.
